### ISSUE TITLE
None of your *.ipynb notebooks are loading in the GitHub notebook viewer

### ISSUE THREAD

**Issue by mhr** [cod3licious/simec#1]
![image](https://user-images.githubusercontent.com/1429247/39391348-c9a26814-4a6f-11e8-81b3-83f790090018.png)

For some reason, they all give me a "Something went wrong. Reload?" error message. I had to download the repo and open them in Jupyter locally to be able to view them.

**Comment by cod3licious** [comment]
yes, i noticed that as well, however it works today, so i think this was an issue on githubs side
